metiers:
  mineur:
    '2':
      - '1:0:1'
      - '2:0:1'
    '3':
      - '1:0:1'
      - '2:0:1'
    '4':
      - '1:0:1'
      - '2:0:1'
    '5':
      - '1:0:1'
      - '2:0:1'
  bucheron:
    '2':
      - '1:0:6'
      - '2:0:1'
    '3':
      - '2:0:6'
      - '3:0:1'
      - '2804:13:1:Test Chisel'
    '4':
      - '1:0:1'
      - '2:0:1'
    '5':
      - '1:0:1'
      - '2:0:1'
  chasseur:
    '2':
      - '1:0:1'
      - '2:0:1'
    '3':
      - '1:0:1'
      - '2:0:1'
    '4':
      - '1:0:1'
      - '2:0:1'
    '5':
      - '1:0:1'
      - '2:0:1'
  dresseur:
    '2':
      - '1:0:1'
      - '2:0:1'
    '3':
      - '1:0:1'
      - '2:0:1'
    '4':
      - '1:0:1'
      - '2:0:1'
    '5':
      - '1:0:1'
      - '2:0:1'
  ingenieur:
    '2':
      - '1:0:1'
      - '2:0:1'
    '3':
      - '1:0:1'
      - '2:0:1'
    '4':
      - '1:0:1'
      - '2:0:1'
    '5':
      - '1:0:1'
      - '2:0:1'
  policier:
    '2':
      - '1:0:1'
      - '2:0:1'
    '3':
      - '1:0:1'
      - '2:0:1'
    '4':
      - '1:0:1'
      - '2:0:1'
    '5':
      - '1:0:1'
      - '2:0:1'
  mafieux:
    '2':
      - '1:0:1'
      - '2:0:1'
    '3':
      - '1:0:1'
      - '2:0:1'
    '4':
      - '1:0:1'
      - '2:0:1'
    '5':
      - '1:0:1'
      - '2:0:1'